root: true

extends:
  - standard

rules:
  comma-dangle: 
    - error
    - always-multiline
  indent:
    - error
    - 2
    - SwitchCase: 1
      MemberExpression: off
  no-undef: error
  no-unused-vars: off
  operator-linebreak:
    - error
    - before
